//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medidorModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lectura
    {
        public int id_lectura { get; set; }
        public Nullable<int> id_medidor { get; set; }
        public byte[] fecha { get; set; }
        public string consumo { get; set; }
    }
}
